"""remove unique from item_id

Revision ID: 007ad6c710e8
Revises: b98a46e91684
Create Date: 2026-04-03 15:27:57.584530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007ad6c710e8'
down_revision = 'b98a46e91684'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('remarks_item_id_key', 'remarks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('remarks_item_id_key', 'remarks', ['item_id'])
    # ### end Alembic commands ###
