"""auto migration

Revision ID: 035e2c7ee65b
Revises: 66285b8d0b09
Create Date: 2026-03-31 17:32:37.673998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035e2c7ee65b'
down_revision = '66285b8d0b09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
