"""Initial migration

Revision ID: 3033bff23af2
Revises: 
Create Date: 2026-03-31 15:17:39.839535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3033bff23af2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SUPERVISOR', 'OPERATOR', 'VIEWER', name='rolelevel'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('department',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dept_type', sa.Enum('PRODUCTION', 'QUALITY_ASSURANCE', 'PACKAGING', 'SHIPPING', 'WAREHOUSE', 'MANAGEMENT', name='departmentenum'), nullable=False),
    sa.Column('head_of_department', sa.UUID(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['head_of_department'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qr_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('registered_by', sa.UUID(), nullable=True),
    sa.Column('enabled_by', sa.UUID(), nullable=True),
    sa.Column('enabled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['enabled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produced_items',
    sa.Column('produced_id', sa.UUID(), nullable=False),
    sa.Column('qr_code_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('approval_id', sa.UUID(), nullable=False),
    sa.Column('produced_date', sa.DateTime(), nullable=True),
    sa.Column('final_department', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['final_department'], ['department.id'], ),
    sa.ForeignKeyConstraint(['qr_code_id'], ['qr_codes.id'], ),
    sa.PrimaryKeyConstraint('produced_id')
    )
    op.create_table('production_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('qr_code_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('session_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_by', sa.UUID(), nullable=True),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('voided_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['qr_code_id'], ['qr_codes.id'], ),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('qr_code_id', sa.UUID(), nullable=False),
    sa.Column('scanned_by', sa.UUID(), nullable=False),
    sa.Column('department', sa.UUID(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department'], ['department.id'], ),
    sa.ForeignKeyConstraint(['qr_code_id'], ['qr_codes.id'], ),
    sa.ForeignKeyConstraint(['scanned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['production_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_events')
    op.drop_table('production_sessions')
    op.drop_table('produced_items')
    op.drop_table('qr_codes')
    op.drop_table('department')
    op.drop_table('users')
    # ### end Alembic commands ###
