"""add phone to user model

Revision ID: 66285b8d0b09
Revises: 3033bff23af2
Create Date: 2026-03-31 16:38:12.602565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66285b8d0b09'
down_revision = '3033bff23af2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))

    # Backfill existing rows so NOT NULL can be applied safely.
    op.execute(
        """
        UPDATE users
        SET phone_number = 'temp_' || REPLACE(id::text, '-', '')
        WHERE phone_number IS NULL
        """
    )

    op.alter_column('users', 'phone_number', nullable=False)
    op.create_unique_constraint('uq_users_phone_number', 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_phone_number', 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
