"""Add remarks_history and updated_at

Revision ID: 8c24cc53fef0
Revises: 007ad6c710e8
Create Date: 2026-04-03 17:16:05.798337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c24cc53fef0'
down_revision = '007ad6c710e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remarks', sa.Column('remarks_history', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('remarks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remarks', 'updated_at')
    op.drop_column('remarks', 'remarks_history')
    # ### end Alembic commands ###
