"""models edited

Revision ID: 907b33b5cb54
Revises: b8f14e2c3a11
Create Date: 2026-04-01 16:34:11.006546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '907b33b5cb54'
down_revision = 'b8f14e2c3a11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE produced_items DROP CONSTRAINT IF EXISTS produced_items_qr_code_id_fkey")
    op.execute("ALTER TABLE remarks DROP CONSTRAINT IF EXISTS remarks_qr_id_fkey")
    op.execute("ALTER TABLE remarks DROP CONSTRAINT IF EXISTS fk_remarks_qr_id_qr_codes")
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'qr_status') THEN
                CREATE TYPE qr_status AS ENUM ('pending', 'active', 'inactive');
            END IF;
        END $$;
        """
    )

    op.alter_column('qr_codes', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               postgresql_using='id::text',
               existing_nullable=False)

    op.alter_column('produced_items', 'qr_code_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               postgresql_using='qr_code_id::text',
               existing_nullable=False)

    op.alter_column('remarks', 'qr_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               postgresql_using='qr_id::text',
               existing_nullable=True)

    op.create_foreign_key('produced_items_qr_code_id_fkey', 'produced_items', 'qr_codes', ['qr_code_id'], ['id'])
    op.create_foreign_key('fk_remarks_qr_id_qr_codes', 'remarks', 'qr_codes', ['qr_id'], ['id'])

    op.alter_column('qr_codes', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('pending', 'active', 'inactive', name='qr_status'),
               postgresql_using="lower(status::text)::qr_status",
               nullable=False)
    op.alter_column('qr_codes', 'registered_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('qr_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE remarks DROP CONSTRAINT IF EXISTS remarks_qr_id_fkey")
    op.execute("ALTER TABLE remarks DROP CONSTRAINT IF EXISTS fk_remarks_qr_id_qr_codes")
    op.execute("ALTER TABLE produced_items DROP CONSTRAINT IF EXISTS produced_items_qr_code_id_fkey")

    op.alter_column('qr_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('qr_codes', 'registered_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('qr_codes', 'status',
               existing_type=sa.Enum('pending', 'active', 'inactive', name='qr_status'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('qr_codes', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               postgresql_using='id::uuid',
               existing_nullable=False)

    op.alter_column('remarks', 'qr_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               postgresql_using='NULLIF(qr_id, \'\')::uuid',
               existing_nullable=True)

    op.alter_column('produced_items', 'qr_code_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               postgresql_using='qr_code_id::uuid',
               existing_nullable=False)

    op.create_foreign_key('produced_items_qr_code_id_fkey', 'produced_items', 'qr_codes', ['qr_code_id'], ['id'])
    op.create_foreign_key('fk_remarks_qr_id_qr_codes', 'remarks', 'qr_codes', ['qr_id'], ['id'])
    # ### end Alembic commands ###
