"""Update QRCode schema

Revision ID: ac66e6c8219c
Revises: 035e2c7ee65b
Create Date: 2026-04-01 14:50:31.116999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac66e6c8219c'
down_revision = '035e2c7ee65b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('produced_items_qr_code_id_fkey', 'produced_items', type_='foreignkey')
    op.drop_constraint('production_sessions_qr_code_id_fkey', 'production_sessions', type_='foreignkey')
    op.drop_constraint('scan_events_qr_code_id_fkey', 'scan_events', type_='foreignkey')

    op.alter_column('produced_items', 'qr_code_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False,
               postgresql_using='qr_code_id::varchar')
    op.alter_column('production_sessions', 'qr_code_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False,
               postgresql_using='qr_code_id::varchar')
    op.alter_column('qr_codes', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False,
               postgresql_using='id::varchar')
    postgresql.ENUM('pending', 'active', 'inactive', name='qr_status').create(op.get_bind())
    op.alter_column('qr_codes', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('pending', 'active', 'inactive', name='qr_status'),
               nullable=False,
               postgresql_using='status::qr_status')
    op.alter_column('qr_codes', 'registered_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('qr_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('scan_events', 'qr_code_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False,
               postgresql_using='qr_code_id::varchar')

    op.create_foreign_key('produced_items_qr_code_id_fkey', 'produced_items', 'qr_codes', ['qr_code_id'], ['id'])
    op.create_foreign_key('production_sessions_qr_code_id_fkey', 'production_sessions', 'qr_codes', ['qr_code_id'], ['id'])
    op.create_foreign_key('scan_events_qr_code_id_fkey', 'scan_events', 'qr_codes', ['qr_code_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_events', 'qr_code_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('qr_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('qr_codes', 'registered_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('qr_codes', 'status',
               existing_type=sa.Enum('pending', 'active', 'inactive', name='qr_status'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('qr_codes', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('production_sessions', 'qr_code_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('produced_items', 'qr_code_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
