"""refactor_departments_table_schema

Revision ID: af3c73c7a6a3
Revises: 2c8f146968e5
Create Date: 2026-04-02 23:46:46.110647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af3c73c7a6a3'
down_revision = '2c8f146968e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('department', sa.Column('sequence_order', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'department', ['name'])
    op.drop_column('department', 'dept_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('dept_type', postgresql.ENUM('PRODUCTION', 'QUALITY_ASSURANCE', 'PACKAGING', 'SHIPPING', 'WAREHOUSE', 'MANAGEMENT', name='departmentenum'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'department', type_='unique')
    op.drop_column('department', 'sequence_order')
    op.drop_column('department', 'name')
    # ### end Alembic commands ###
