"""Make item_id unique in remarks

Revision ID: b98a46e91684
Revises: dce9cb83c5e1
Create Date: 2026-04-03 15:04:08.595667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b98a46e91684'
down_revision = 'dce9cb83c5e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'remarks', ['item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'remarks', type_='unique')
    # ### end Alembic commands ###
