"""make_sequence_order_unique

Revision ID: dce9cb83c5e1
Revises: af3c73c7a6a3
Create Date: 2026-04-03 00:43:04.335376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce9cb83c5e1'
down_revision = 'af3c73c7a6a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Set sequence order uniquely to distinct values to avoid collisions
    op.execute(
        "WITH numbered AS (SELECT id, row_number() OVER (ORDER BY created_on ASC) AS rn FROM department) "
        "UPDATE department SET sequence_order = numbered.rn FROM numbered "
        "WHERE department.id = numbered.id;"
    )
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'department', ['sequence_order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department', type_='unique')
    # ### end Alembic commands ###
