"""Add custom_data to remarks

Revision ID: e404eb2b2f1c
Revises: 8c24cc53fef0
Create Date: 2026-04-03 18:10:59.993577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e404eb2b2f1c'
down_revision = '8c24cc53fef0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remarks', sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remarks', 'custom_data')
    # ### end Alembic commands ###
