"""auto migration

Revision ID: e49463e9160d
Revises: 531ffbc49d1b
Create Date: 2026-04-02 17:05:52.577592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e49463e9160d'
down_revision = '531ffbc49d1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE qr_codes SET status = 'inactive' WHERE status::text = 'pending'")
    op.execute("CREATE TYPE qr_status_enum AS ENUM('active', 'inactive')")
    op.execute("ALTER TABLE qr_codes ALTER COLUMN status TYPE qr_status_enum USING status::text::qr_status_enum")
    op.execute("DROP TYPE qr_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE qr_codes SET status = 'inactive' WHERE status = 'pending'");op.execute("ALTER TABLE qr_codes ALTER COLUMN status TYPE qr_status USING status::text::qr_status");op.alter_column('qr_codes', 'status',
               existing_type=sa.Enum('active', 'inactive', name='qr_status_enum'),
               type_=postgresql.ENUM('pending', 'active', 'inactive', name='qr_status'),
               existing_nullable=False)
    # ### end Alembic commands ###
