"""schema_cleanup_v2

Revision ID: f40ba6a7dad8
Revises: 6935082dcee8
Create Date: 2026-05-11 20:08:17.548852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f40ba6a7dad8'
down_revision = '6935082dcee8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Manually drop foreign keys that depend on 'department' table
    op.drop_constraint('fk_remarks_department_id_department', 'remarks', type_='foreignkey')
    
    # 2. Rename department table to departments
    op.rename_table('department', 'departments')
    
    # 3. Alter departments columns explicitly
    op.alter_column('departments', 'created_on', new_column_name='created_at')
    op.drop_constraint('department_head_of_department_fkey', 'departments', type_='foreignkey')
    op.drop_column('departments', 'head_of_department')

    op.create_table('remarks_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('remark_id', sa.UUID(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['remark_id'], ['remarks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.add_column('produced_items', sa.Column('scanned_by', sa.UUID(), nullable=True))
    op.add_column('produced_items', sa.Column('last_edited_by', sa.UUID(), nullable=True))
    op.add_column('produced_items', sa.Column('archived_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('produced_items', sa.Column('department_sequence', sa.Integer(), nullable=False, server_default='-1'))
    op.drop_constraint('produced_items_remark_by_fkey', 'produced_items', type_='foreignkey')
    op.drop_constraint('produced_items_updated_by_fkey', 'produced_items', type_='foreignkey')
    op.drop_constraint('produced_items_created_by_fkey', 'produced_items', type_='foreignkey')
    op.drop_constraint('produced_items_remark_updated_fkey', 'produced_items', type_='foreignkey')
    op.create_foreign_key(None, 'produced_items', 'users', ['scanned_by'], ['id'])
    op.create_foreign_key(None, 'produced_items', 'users', ['last_edited_by'], ['id'])
    op.drop_column('produced_items', 'remark_updated')
    op.drop_column('produced_items', 'remark_by')
    op.drop_column('produced_items', 'updated_by')
    op.drop_column('produced_items', 'created_by')
    op.add_column('qr_codes', sa.Column('last_scanned_at', sa.DateTime(), nullable=True))
    op.add_column('remarks', sa.Column('scanned_by', sa.UUID(), nullable=True))
    op.add_column('remarks', sa.Column('last_edited_by', sa.UUID(), nullable=True))
    op.add_column('remarks', sa.Column('scanned_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.drop_constraint('remarks_remark_updated_fkey', 'remarks', type_='foreignkey')
    op.drop_constraint('remarks_remark_by_fkey', 'remarks', type_='foreignkey')
    op.create_foreign_key(None, 'remarks', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'remarks', 'users', ['scanned_by'], ['id'])
    op.create_foreign_key(None, 'remarks', 'users', ['last_edited_by'], ['id'])
    op.drop_column('remarks', 'remark_updated')
    op.drop_column('remarks', 'remark_by')
    op.add_column('users', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deactivated_at')
    op.add_column('remarks', sa.Column('remark_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('remarks', sa.Column('remark_updated', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'remarks', type_='foreignkey')
    op.drop_constraint(None, 'remarks', type_='foreignkey')
    op.drop_constraint(None, 'remarks', type_='foreignkey')
    op.create_foreign_key('remarks_remark_by_fkey', 'remarks', 'users', ['remark_by'], ['id'])
    op.create_foreign_key('fk_remarks_department_id_department', 'remarks', 'department', ['department_id'], ['id'])
    op.create_foreign_key('remarks_remark_updated_fkey', 'remarks', 'users', ['remark_updated'], ['id'])
    op.drop_column('remarks', 'scanned_at')
    op.drop_column('remarks', 'last_edited_by')
    op.drop_column('remarks', 'scanned_by')
    op.drop_column('qr_codes', 'last_scanned_at')
    op.add_column('produced_items', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('produced_items', sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('produced_items', sa.Column('remark_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('produced_items', sa.Column('remark_updated', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'produced_items', type_='foreignkey')
    op.drop_constraint(None, 'produced_items', type_='foreignkey')
    op.create_foreign_key('produced_items_remark_updated_fkey', 'produced_items', 'users', ['remark_updated'], ['id'])
    op.create_foreign_key('produced_items_created_by_fkey', 'produced_items', 'users', ['created_by'], ['id'])
    op.create_foreign_key('produced_items_updated_by_fkey', 'produced_items', 'users', ['updated_by'], ['id'])
    op.create_foreign_key('produced_items_remark_by_fkey', 'produced_items', 'users', ['remark_by'], ['id'])
    op.drop_column('produced_items', 'department_sequence')
    op.drop_column('produced_items', 'archived_at')
    op.drop_column('produced_items', 'last_edited_by')
    op.drop_column('produced_items', 'scanned_by')
    op.create_table('department',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('head_of_department', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'inactive', name='departmentstatus'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('sequence_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['head_of_department'], ['users.id'], name='department_head_of_department_fkey'),
    sa.PrimaryKeyConstraint('id', name='department_pkey'),
    sa.UniqueConstraint('name', name='department_name_key'),
    sa.UniqueConstraint('sequence_order', name='department_sequence_order_key')
    )
    op.drop_table('remarks_audit_log')
    op.drop_table('departments')
    # ### end Alembic commands ###
